version: "4.30.0"
# mysql:8.4://atm-db
services:
  atm-db:
    image: mysql:8.4
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql_scripts:/sql_scripts
    environment:
      MYSQL_DATABASE: atm-db
      MYSQL_ROOT_PASSWORD: set-your-password

  # myzookeeper:
  #   image: zookeeper
  #   restart: always
  # mykafkaserver:
  #   image: apache/kafka
  #   links: 
  #     - myzookeeper:zookeeper
  #   depends_on:
  #     - myzookeeper
  set-up:
    build:
      dockerfile: Dockerfile.setup
    depends_on:
      - atm-db


  
  

#  kafka:
#    depends_on:
#      - atm-db